#!/usr/bin/env python3
"""Builds Resources/en.lproj/Localizable.strings from scripts/l10n/en.json.
Fails when a key used in the code has no translation or placeholders differ."""
import json, os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.chdir(ROOT)

def swift_unescape(s):
    out, i = [], 0
    while i < len(s):
        if s[i] == '\\' and i + 1 < len(s):
            c = s[i + 1]
            out.append({'n': '\n', 't': '\t', '"': '"', '\\': '\\', "'": "'", '0': '\0'}.get(c, '\\' + c))
            i += 2
        else:
            out.append(s[i]); i += 1
    return ''.join(out)

def strings_escape(s):
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\t', '\\t')

raw = json.loads(subprocess.check_output([sys.executable, 'scripts/l10n/extract_keys.py']))
keys = [swift_unescape(k) for k in raw]
translations = json.load(open('scripts/l10n/en.json'))

missing = [k for k in keys if k not in translations]
unused = [k for k in translations if k not in keys]
bad = [k for k in keys if k in translations and
       re.findall(r'%[@%]', k) != re.findall(r'%[@%]', translations[k])]
for k in missing: print('MISSING:', k, file=sys.stderr)
for k in bad: print('PLACEHOLDERS DIFFER:', k, file=sys.stderr)
for k in unused: print('unused translation:', k)
if missing or bad:
    sys.exit(1)

os.makedirs('Resources/en.lproj', exist_ok=True)
with open('Resources/en.lproj/Localizable.strings', 'w') as f:
    f.write('/* Generated by scripts/l10n/make_strings.py from scripts/l10n/en.json. Keys are the Russian texts. */\n\n')
    for k in keys:
        f.write(f'"{strings_escape(k)}" = "{strings_escape(translations[k])}";\n')
print(f'{len(keys)} strings -> Resources/en.lproj/Localizable.strings')
