import Foundation

/// Strings are written in Russian in the code and serve as keys; English comes from en.lproj/Localizable.strings
/// (generated by scripts/l10n/make_strings.py). The interface takes the localization macOS itself picks for the app
/// from the user's languages: the first of them Subline has, English when it has none. So with the languages (uk, ru)
/// it is Russian, like the menus and panels macOS draws for the app, and the two never mix. A language chosen for
/// Subline in System Settings → Language & Region → Applications wins.
public enum Localization {
    /// "ru" or "en" for this launch.
    public static let current: String = {
        // A development build without the bundle has no translations: the keys are Russian.
        guard Bundle.main.path(forResource: "en", ofType: "lproj") != nil else { return "ru" }
        // Before anything else asks the bundle for its localizations: it keeps the first answer.
        forgetOldChoice()
        return Bundle.main.preferredLocalizations.first?.hasPrefix("ru") == true ? "ru" : "en"
    }()

    /// Subtits (the app's earlier name) picked Russian whenever it was among the Mac's languages and wrote that into
    /// the app's own language list; such an entry would now look like a choice made in System Settings. A language
    /// picked by hand in the old settings stays, as if it had been chosen in System Settings.
    private static func forgetOldChoice() {
        let defaults = UserDefaults.standard
        guard let id = Bundle.main.bundleIdentifier, let domain = defaults.persistentDomain(forName: id),
              let applied = domain[FormerName.appliedLanguageKey] as? String else { return }
        let picked = domain[FormerName.languageKey] as? String
        if picked == nil || picked == "automatic", let written = (domain["AppleLanguages"] as? [String])?.first,
           written.hasPrefix(applied) {
            defaults.removeObject(forKey: "AppleLanguages")
        }
        defaults.removeObject(forKey: FormerName.appliedLanguageKey)
        defaults.removeObject(forKey: FormerName.languageKey)
    }

    /// Call as early as possible at launch.
    public static func apply() {
        _ = current
    }

    /// The interface language in its own name, for Settings.
    public static var currentName: String {
        current == "ru" ? "Русский" : "English"
    }

    /// Number style of the interface language for sizes inside texts ("1,08 ГБ" in Russian, "1.08 GB" in English).
    public static let numberLocale = Locale(identifier: current == "ru" ? "ru_RU" : "en_US")

    static func string(_ key: String) -> String {
        bundle?.localizedString(forKey: key, value: key, table: nil) ?? key
    }

    private static let bundle: Bundle? = {
        guard current != "ru", let path = Bundle.main.path(forResource: current, ofType: "lproj") else { return nil }
        return Bundle(path: path)
    }()
}

/// File size written in the number style of the interface language.
public func formatBytes(_ count: Int64) -> String {
    count.formatted(.byteCount(style: .file).locale(Localization.numberLocale))
}

/// Localized string. `key` is the Russian text; `%@` placeholders are filled with `args`.
public func L(_ key: String, _ args: CVarArg...) -> String {
    let text = Localization.string(key)
    return args.isEmpty ? text : String(format: text, arguments: args)
}
